services:
  upload:
    build: ./upload-service
    ports:
      - 3000:3000
    depends_on:
      - redis
    env_file:
      - ./deploy-service/.env
  deploy:
    build: ./deploy-service
    depends_on:
      - redis
    env_file:
      - ./upload-service/.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379